### ISSUE TITLE
No access to Trello board

### ISSUE THREAD

**Issue by adamrybinski** [maryiafrantsava-deriv/slavic.js#6]
@nikita-deriv @maryiafrantsava-deriv 
I have no access to trello board on adamrbnr at gmail . Pls send additional inv if you can

**Comment by maryiafrantsava-deriv** [comment]
> @nikita-deriv @maryiafrantsava-deriv I have no access to trello board on adamrbnr at gmail . Pls send additional inv if you can

fixed
